#!/usr/bin/env bash
# IMP-15: generate ops/rocketchat/.env from secrets/rocketchat.env (no stdout secrets)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="${RC_SECRETS_PATH:-$HOME/.grok/agency/secrets/rocketchat.env}"
OUT="${1:-$ROOT/.env}"
PIN_FILE="${RC_PUBLIC_DOMAIN_FILE:-$ROOT/PUBLIC_DOMAIN}"
umask 077
# shellcheck disable=SC1090
set -a
source "$SECRETS"
set +a

ROOT_URL_VAL="${ROCKETCHAT_ROOT_URL:-${ROCKETCHAT_PUBLIC_URL:-http://localhost:3000}}"
# Never emit the Cujo-blocked free domain into compose env.
if [[ "$ROOT_URL_VAL" == *"ngrok-free.dev"* ]] || [[ "$ROOT_URL_VAL" == *"cash-scalded-enhance"* ]]; then
  echo "generate_compose_env: refusing ROOT_URL with blocked free domain: $ROOT_URL_VAL" >&2
  echo "generate_compose_env: set ROCKETCHAT_ROOT_URL to https://velocityworks-rc.ngrok.app" >&2
  exit 1
fi
canonical="$(grep -E -v '^\s*(#|$)' "$PIN_FILE" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
if [[ -n "$canonical" && "$ROOT_URL_VAL" != *"$canonical"* && "$ROOT_URL_VAL" != http://localhost* && "$ROOT_URL_VAL" != http://127.0.0.1* ]]; then
  echo "generate_compose_env: ROOT_URL host must match pin $canonical (got $ROOT_URL_VAL)" >&2
  exit 1
fi

{
  echo "# generated by generate_compose_env.sh — do not commit"
  echo "# public host pin: see ops/rocketchat/PUBLIC_DOMAIN (never *.ngrok-free.dev)"
  echo "ROOT_URL=${ROOT_URL_VAL}"
  echo "ADMIN_USERNAME=${ROCKETCHAT_ADMIN_USERNAME:-principal}"
  echo "ADMIN_PASS=${ROCKETCHAT_ADMIN_PASSWORD:?missing ROCKETCHAT_ADMIN_PASSWORD}"
  echo "ADMIN_EMAIL=${ROCKETCHAT_ADMIN_EMAIL:-principal@localhost.local}"
  echo "RC_PORT_BIND=${RC_PORT_BIND:-127.0.0.1}"
} > "$OUT"
chmod 600 "$OUT"
echo "wrote $OUT (mode 600)"
